### ISSUE TITLE
Kaizo: Expert Filter has typo that prevents it from working as intended

### ISSUE THREAD

**Issue by nick-sds** [zuccha/rom-hack-downloader#3]
The typo in the following line appears to be the cause of the Kaizo: Expert filter returning results that are not Kaizo: Expert: 

https://github.com/zuccha/rom-hack-manager/blob/7d8f28736bed1248510387a7ae47e694887c0e18/src/windows/search/useSearchHacks.tsx#L12

Also, I noticed this parameter marked as unknown:

https://github.com/zuccha/rom-hack-manager/blob/7d8f28736bed1248510387a7ae47e694887c0e18/src/windows/search/useSearchHacks.tsx#L148

The u parameter differentiates moderated hacks (0) and waiting hacks (1). If you're looking to add any features, it would be cool to have another dropdown in the search that controlled that value so you can find and download waiting hacks as well.

Anyway, I hope this informal issue write-up is ok. I really enjoy the tool and find it super helpful, thank you for creating it!

**Comment by zuccha** [comment]
> The typo in the following line appears to be the cause of the Kaizo: Expert filter returning results that are not Kaizo: Expert:

Well, quite embarrassing on my part considering I made a commit named "fix SMW search by type" smh

> The u parameter differentiates moderated hacks (0) and waiting hacks (1).

Nice! This is really useful, considering as of now it was impossible to search for a subset of the hacks.
